# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in docusearch-api.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21", group: :development

gem "sorbet", "~> 0.5.11148", group: :development

gem "faker", "~> 3.2"

gem "elasticsearch", "~> 7.17"

gem "rack", "~> 3.0"

gem "falcon", "~> 0.42.3"
