version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
    volumes:
      - docusearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docusearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    volumes:
      - docusearch:/usr/share/elasticsearch/data
    ports:
      - 5601:5601
    networks:
      - docusearch

volumes:
  docusearch:

networks:
  docusearch:
