version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
    volumes:
      - docusearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docusearch

volumes:
  docusearch:

networks:
  docusearch:
