# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/docusearch-api/all/docusearch-api.rbi
#
# docusearch-api-0.1.0

module Docusearch
end
module Docusearch::Api
end
class Docusearch::Api::Error < StandardError
end
